import { Coins, Flame, AlertCircle, MessageSquareWarning, Bell } from "lucide-react";


export default function Overview() {
    return (
        <div className="flex-1 flex flex-col p-8 gap-6">
            <h1 className="text-zinc-700 font-medium text-xl">Quick overview</h1>
            <div className="w-full grid grid-cols-1 md:grid-cols-3 xl:grid-cols-5 gap-5">
                {/* Tokens */}
                <div className="bg-white rounded-xl p-5 border shadow-sm hover:shadow-lg transition flex flex-col justify-between h-[170px]">
                    <div>
                        <div className="flex items-center gap-2 text-gray-700">
                            <Coins size={18} className="text-yellow-500" />
                            <h2 className="text-sm font-semibold uppercase tracking-wide">Token Balance</h2>
                        </div>
                        <p className="text-sm text-gray-500 mt-2">
                            Total tokens available in your account
                        </p>
                    </div>
                    <div className="text-right text-2xl font-semibold text-gray-800">
                        2,300 T
                    </div>
                </div>

                {/* Burn Rate */}
                <div className="bg-white rounded-xl p-5 border shadow-sm hover:shadow-lg transition flex flex-col justify-between h-[170px]">
                    <div>
                        <div className="flex items-center gap-2 text-gray-700">
                            <Flame size={18} className="text-red-500" />
                            <h2 className="text-sm font-semibold uppercase tracking-wide">Usage Rate</h2>
                        </div>
                        <p className="text-sm text-gray-500 mt-2">
                            Tokens consumed per hour by active agents
                        </p>
                    </div>
                    <div className="text-right text-2xl font-semibold text-gray-800">
                        30 T/hr
                    </div>
                </div>

                {/* Task Approval */}
                <div className="bg-white rounded-xl p-5 border shadow-sm hover:shadow-lg transition flex flex-col justify-between h-[170px]">
                    <div>
                        <div className="flex items-center gap-2 text-gray-700">
                            <AlertCircle size={18} className="text-orange-500" />
                            <h2 className="text-sm font-semibold uppercase tracking-wide">Pending Approvals</h2>
                        </div>
                        <p className="text-sm text-gray-500 mt-2">
                            Tasks awaiting your review and confirmation
                        </p>
                    </div>
                    <div className="text-right text-2xl font-semibold text-gray-800">
                        24
                    </div>
                </div>

                {/* Reports */}
                <div className="bg-white rounded-xl p-5 border shadow-sm hover:shadow-lg transition flex flex-col justify-between h-[170px]">
                    <div>
                        <div className="flex items-center gap-2 text-gray-700">
                            <MessageSquareWarning size={18} className="text-purple-500" />
                            <h2 className="text-sm font-semibold uppercase tracking-wide">System Reports</h2>
                        </div>
                        <p className="text-sm text-gray-500 mt-2">
                            Reports generated by monitoring agents
                        </p>
                    </div>
                    <div className="text-right text-2xl font-semibold text-gray-800">
                        4
                    </div>
                </div>

                {/* Notifications */}
                <div className="bg-white rounded-xl p-5 border shadow-sm hover:shadow-lg transition flex flex-col justify-between h-[170px]">
                    <div>
                        <div className="flex items-center gap-2 text-gray-700">
                            <Bell size={18} className="text-blue-500" />
                            <h2 className="text-sm font-semibold uppercase tracking-wide">Notifications</h2>
                        </div>
                        <p className="text-sm text-gray-500 mt-2">
                            Updates and alerts from system activity
                        </p>
                    </div>
                    <div className="text-right text-2xl font-semibold text-gray-800">
                        27
                    </div>
                </div>

            </div>
        </div>
    )
}